### ISSUE TITLE
Mock struct in external crate does not work

### ISSUE THREAD

**Issue by kungfucop** [nrxus/faux#26] opened 2020-03-12 05:59 UTC
```rust
// crate1
#[cfg_attr(test, faux::create)]
pub struct SettingApi;

#[cfg_attr(test, faux::methods)]
impl SettingApi {
    pub fn get_settings(){}
}

//crate2
mod tests {
    use crate1::SettingApi
    #[test]
    fn testReal() {
        let mut api = SettingApi::faux();
        faux::when!(api.get_settings).safe_then(|req_cmd| {
             // print something
        });
    }
}
```

```
Error error[E0599]: no function or associated item named `faux` found for type `SettingApi` in the current scope
```

**Comment by nrxus** [comment] 2020-03-12 21:12
I took the liberty of editing the formatting of your post a bit, I hope you do not mind it was just a bit hard to read.

Unfortunately, this is the expected behavior due to the way `#[cfg(test)]` works in Rust. When a different crate is pulled over, even if you are running tests, it will not build that dependent crate with the test cfg enabled for them, it will only enable the test cfg within the crate currently being tested. 

For more info: https://stackoverflow.com/questions/41700543/can-we-share-test-utilites-between-crates.

Eventually I want to provide workarounds for this limitation, or at least specified suggestions within a small guide of how to make it work but it couldn't be through the `#[cfg(test]` unfortunately.

**Comment by kungfucop** [comment] 2020-03-12 21:17
Thank you @nrxus for the answer. Please keep the good work going, I search all github trying to find something could mock my db/network calls easily.  Feel there is a lot potential in faux! 

A guide on how to work around this for now will be super helpful!!

**Comment by nrxus** [comment] 2020-03-13 15:26
I also feel like there is a lot of potential here, thanks for looking at `faux`!

I created a [new issue](https://github.com/nrxus/faux/issues/27) specifically about exploring and documenting a way to export mocks through crates so I am going to close this one.

**Closed by nrxus** 2020-03-13 15:26 UTC
